version: 2.1
commands:
  authenticate-gcloud:
    steps:
      - run:
          name: gcloud を認証する
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > gcloud-service-key.json
            gcloud auth activate-service-account --key-file gcloud-service-key.json
            gcloud auth configure-docker --quiet asia-northeast1-docker.pkg.dev
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker イメージを作る
          command: docker build --tag asia-northeast1-docker.pkg.dev/gestational-calendar/server/server .
      - authenticate-gcloud
      - run:
          name: Docker イメージをいったんプッシュする
          command: docker push asia-northeast1-docker.pkg.dev/gestational-calendar/server/server
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - authenticate-gcloud
      - run:
          name: Serverless Engine にデプロイする
          command: gcloud run deploy server --region asia-northeast1 --image asia-northeast1-docker.pkg.dev/gestational-calendar/server/server --project gestational-calendar --platform managed

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
